version: '3'
services:
  backend:
    image: node:16
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - MODE=${MODE}
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
    volumes:
      - ./backend/src:/app
    working_dir: /app
    ports:
      - 3001:3001
    expose:
      - 3001

  frontend:
    image: node:alpine
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - MODE=${MODE}
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
    volumes:
      - ./frontend/src:/app
    working_dir: /app
    ports:
      - 3000:3000
    expose:
      - 3000
